# Generated by Django 4.0.2 on 2022-05-11 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_companyview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyview',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.company'),
        ),
    ]
