# Generated by Django 4.0.2 on 2022-05-12 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_companyview_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='job',
            name='users',
            field=models.ManyToManyField(related_name='jobs', through='jobs.UserApply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userapply',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_applied', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='userapply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_applied', to=settings.AUTH_USER_MODEL),
        ),
    ]
