# Generated by Django 4.0.2 on 2022-05-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_userapply_job_users_userapply_job_userapply_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='users',
        ),
        migrations.DeleteModel(
            name='UserApply',
        ),
    ]
