# Generated by Django 4.0.2 on 2022-05-12 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_users_delete_userapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvonline',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CVOnlines', to='jobs.company'),
        ),
    ]
