# Generated by Django 4.0.2 on 2022-05-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_cvonline_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVApplyCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.cvonline')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
            ],
        ),
    ]
